This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 30-Aug-2016 at 19:40:12.
Results are based upon data input from "WindPACT_5.0MW_TwrModes.inp".

Rigid beam length (m)    =     0.000
Flexible beam length (m) =   151.072
Total beam length (m)    =   151.072
End mass (kg)            =396638.344
Mass multiplier          =     1.000
Stiffness multiplier     =     1.000

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      0.2421      1.6100      4.6209     10.8648     18.0741

    x^2         0.6667    -21.1687     81.1722   -659.4668   1253.2566
    x^3         0.5282     14.8317    242.0122   3349.0437  -9265.3027
    x^4        -0.7659    -28.6991  -1541.9224  -5486.5610  23622.5117
    x^5         1.2015     76.6729   1945.4833   3264.7114 -25057.9082
    x^6        -0.6305    -40.6368   -725.7452   -466.7274   9448.4414
