This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 30-Aug-2016 at 19:40:12.
Results are based upon data input from "WindPACT_0.75MW_TwrModes.inp".

Rigid beam length (m)    =     0.000
Flexible beam length (m) =    58.670
Total beam length (m)    =    58.670
End mass (kg)            = 27524.180
Mass multiplier          =     1.000
Stiffness multiplier     =     1.000

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      0.6079      4.1640     12.0062     28.2712     46.1310

    x^2         0.8565    -21.2482     86.6210   -910.5667    677.0902
    x^3         0.3408      9.2212    123.2327   5156.8755  -5162.4561
    x^4        -0.3653     10.6976  -1202.0079 -10034.7549  13500.3203
    x^5         0.4353     21.0894   1629.9080   8061.4404 -14617.8789
    x^6        -0.2673    -18.7600   -636.7537  -2271.9946   5603.9248
