This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 30-Aug-2016 at 19:40:12.
Results are based upon data input from "WindPACT_1.5MW_BldModes.inp".

Rigid beam length (m)    =     0.000
Flexible beam length (m) =    35.000
Total beam length (m)    =    35.000
End mass (kg)            =     0.000
Rotor speed (rpm)        =    20.463
Pitch angle (deg)        =     0.000
Mass multiplier          =     1.000
Flatwise stiffness mult. =     1.000
Edgewise stiffness mult. =     1.000


Out-of-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      0.8562      2.4348      5.5025     11.3511     44.2288

    x^2         0.0809     -0.2649      0.0167     -0.5243     39.7539
    x^3         2.1356     -3.1596     25.3670    -20.3379   -285.8095
    x^4        -2.3661     -0.9342    -90.8759    104.7859    720.9147
    x^5         1.9659     12.9796    100.2661   -161.6854   -766.2548
    x^6        -0.8163     -7.6209    -33.7739     78.7617    292.3958


In-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      1.2133      4.1249      9.4842     26.0901     51.8757

    x^2         0.3121     -0.8050      1.1085     -7.4856     26.0563
    x^3         3.8700     -8.2134     28.9994     31.0105   -194.4912
    x^4        -7.9390     21.7250   -125.4568    -24.4351    506.9831
    x^5         7.3668    -13.9422    158.5284    -26.9652   -554.7171
    x^6        -2.6099      2.2356    -62.1795     28.8754    217.1689
