This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 30-Aug-2016 at 19:40:12.
Results are based upon data input from "WindPACT_3.0MW_TwrModes.inp".

Rigid beam length (m)    =     0.000
Flexible beam length (m) =   116.731
Total beam length (m)    =   116.731
End mass (kg)            =194268.375
Mass multiplier          =     1.000
Stiffness multiplier     =     1.000

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      0.3148      2.1990      6.3464     14.9699     29.9252

    x^2         0.7027    -23.6164     95.0765   -751.2111   1503.5111
    x^3         0.5003     14.9349    227.5410   3896.7146 -11075.3711
    x^4        -0.6986    -21.7838  -1619.3446  -6617.1460  28125.1641
    x^5         1.0585     71.2400   2085.3379   4239.2417 -29719.1484
    x^6        -0.5628    -39.7747   -787.6109   -766.5986  11166.8447
