This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 30-Aug-2016 at 19:40:12.
Results are based upon data input from "WindPACT_5.0MW_BldModes.inp".

Rigid beam length (m)    =     3.200
Flexible beam length (m) =    60.800
Total beam length (m)    =    64.000
End mass (kg)            =     0.000
Rotor speed (rpm)        =    11.191
Pitch angle (deg)        =     0.000
Mass multiplier          =     1.000
Flatwise stiffness mult. =     1.000
Edgewise stiffness mult. =     1.000


Out-of-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      0.3451      0.8856      1.9024      3.9450     20.8420

    x^2         0.1044     -0.2728      0.0668     -0.8541     31.5794
    x^3         2.6449     -3.6448     24.3905    -18.7849   -234.2797
    x^4        -3.4286      1.2150    -87.9087    102.3742    605.7240
    x^5         2.6119     10.2980     97.0743   -160.2883   -656.7527
    x^6        -0.9325     -6.5955    -32.6228     78.5530    254.7290


In-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      0.4429      1.4106      3.2064      8.6786     26.7251

    x^2         0.3379     -0.8233      1.2567     -7.6571     26.5559
    x^3         4.0433     -8.1243     27.6123     32.0910   -200.6885
    x^4        -8.5067     21.7244   -121.4981    -26.8379    526.8276
    x^5         7.9119    -14.1155    154.0666    -24.6975   -578.5702
    x^6        -2.7863      2.3387    -60.4375     28.1015    226.8752
