This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 30-Aug-2016 at 19:40:12.
Results are based upon data input from "WindPACT_0.75MW_BldModes.inp".

Rigid beam length (m)    =     1.250
Flexible beam length (m) =    23.750
Total beam length (m)    =    25.000
End mass (kg)            =     0.000
Rotor speed (rpm)        =    28.648
Pitch angle (deg)        =     0.000
Mass multiplier          =     1.000
Flatwise stiffness mult. =     1.000
Edgewise stiffness mult. =     1.000


Out-of-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      1.7218      5.1275     11.8189     24.6932    102.4695

    x^2         0.0734     -0.2631      0.0186     -0.5896     37.4230
    x^3         1.9789     -3.0061     25.2163    -20.1231   -271.1445
    x^4        -2.0928     -1.6204    -90.1257    104.6791    688.1794
    x^5         1.8661     13.8317     99.1340   -161.8874   -735.1706
    x^6        -0.8256     -7.9422    -33.2432     78.9210    281.7127


In-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      2.5527      8.8746     20.5551     56.6120    126.3707

    x^2         0.3043     -0.8017      1.1489     -7.4535     26.5645
    x^3         3.8107     -8.2107     28.6968     30.8104   -198.8640
    x^4        -7.7536     21.6295   -124.6328    -23.9916    519.0352
    x^5         7.1940    -13.7786    157.5931    -27.3838   -568.0571
    x^6        -2.5554      2.1615    -61.8060     29.0185    222.3214
