This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 30-Aug-2016 at 19:40:12.
Results are based upon data input from "WindPACT_1.5MW_TwrModes.inp".

Rigid beam length (m)    =     0.000
Flexible beam length (m) =    82.390
Total beam length (m)    =    82.390
End mass (kg)            = 72025.781
Mass multiplier          =     1.000
Stiffness multiplier     =     1.000

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      0.4324      3.0139      8.7181     20.9940     49.7842

    x^2         0.7475    -22.7796     93.9207   -663.6977   1739.7568
    x^3         0.4483     13.5598    187.4327   3398.7324 -12537.8857
    x^4        -0.5805    -13.9084  -1467.2468  -5667.0552  31258.4219
    x^5         0.8549     58.4919   1916.5759   3513.1602 -32527.8926
    x^6        -0.4702    -34.3637   -729.6826   -580.1398  12068.5996
