This mode-shape file was generated by modes v2.22 (29-Apr-2002) on 30-Aug-2016 at 19:40:12.
Results are based upon data input from "WindPACT_3.0MW_BldModes.inp".

Rigid beam length (m)    =     2.480
Flexible beam length (m) =    47.020
Total beam length (m)    =    49.500
End mass (kg)            =     0.000
Rotor speed (rpm)        =    14.469
Pitch angle (deg)        =     0.000
Mass multiplier          =     1.000
Flatwise stiffness mult. =     1.000
Edgewise stiffness mult. =     1.000


Out-of-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      0.5172      1.4017      3.0978      6.3894     25.1747

    x^2         0.0900     -0.2679      0.0262     -0.5890     37.6920
    x^3         2.3339     -3.3468     25.1650    -20.0421   -272.5886
    x^4        -2.7664     -0.0924    -90.3419    104.3639    690.9571
    x^5         2.1932     11.9217     99.7961   -161.4941   -737.4626
    x^6        -0.8507     -7.2145    -33.6454     78.7612    282.4020


In-plane mode shapes:

               Shape 1     Shape 2     Shape 3     Shape 4     Shape 5
               -------     -------     -------     -------     -------
 Freq (hz)      0.6998      2.3141      5.2947     14.4853     30.9499

    x^2         0.3221     -0.8118      1.1486     -7.6766     25.6245
    x^3         3.9348     -8.1790     28.5661     32.2028   -192.3434
    x^4        -8.1523     21.7235   -124.1523    -27.0695    503.3379
    x^5         7.5713    -14.0077    157.0183    -24.4902   -552.2297
    x^6        -2.6759      2.2751    -61.5807     28.0337    216.6107
